apiVersion: v1
kind: Namespace
metadata:
  name: vault-poc
---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: vault-poc
  namespace: vault-poc
spec:
  provider: vault-poc
  parameters:
    objects: |
      array:
        - |
          objectName: $SECRET_NAME
          objectVersion: $SECRET_VERSION
        - |
          objectName: $KEY_NAME
          objectVersion: $KEY_VERSION
---
kind: Pod
apiVersion: v1
metadata:
  name: vault-poc
  namespace: vault-poc
spec:
  terminationGracePeriodSeconds: 0
  containers:
    - image: k8s.gcr.io/e2e-test-images/busybox:1.29
      name: busybox
      imagePullPolicy: IfNotPresent
      command:
        - "/bin/sleep"
        - "10000"
      volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "vault-poc"