apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-poc
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: vault-poc
  name: vault-poc
  namespace: kube-system
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: vault-poc
  template:
    metadata:
      labels:
        app: vault-poc
    spec:
      serviceAccountName: vault-poc
      containers:
        - name: e2e-provider
          image: slaskawi/vault-poc
          imagePullPolicy: Always
          command:
            - "/bin/vault-poc"
          args:
            - --endpoint=unix:///provider/vault-poc.sock
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 50m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsUser: 0
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: "/provider"
              name: providervol
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: NotIn
                    values:
                      - virtual-kubelet
      volumes:
        - name: providervol
          hostPath:
            path: "/etc/kubernetes/secrets-store-csi-providers"